if game.PlaceId == 155615604 then -- checks the game id
print("Loaded PrisonFuckr")
else
game.Players.LocalPlayer:kick("PrisonFuckr: Invalid GameId. TIP: Execute on Prison Life")
end

local library = loadstring(game:HttpGet(('https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wall%20v3')))()
local ESP = loadstring(game:HttpGet("https://kiriot22.com/releases/ESP.lua"))()

local w = library:CreateWindow("PrisonFuckr") -- Creates the window

local b = w:CreateFolder("Movement") -- Creates the folder(U will put here your buttons,etc)

--b:Label("Movement",{
--TextSize = 25; -- Self Explainin
--TextColor = Color3.fromRGB(255,255,255); -- Self Explaining
--BgColor = Color3.fromRGB(69,69,69); -- Self Explaining
    
--}) 

b:Button("Noclip (E)",function()
    loadstring(game:HttpGet('https://pastebin.com/raw/ihfQUFqf'))()
end)

local epic2 = false
b:Toggle("Fling (kinda broken)",function(bool)
   epic2 = bool
   if epic2 then
       power = 250 -- change this to make it more or less powerful

game:GetService('RunService').Stepped:connect(function()
game.Players.LocalPlayer.Character.Head.CanCollide = false
game.Players.LocalPlayer.Character.UpperTorso.CanCollide = false
game.Players.LocalPlayer.Character.LowerTorso.CanCollide = false
game.Players.LocalPlayer.Character.HumanoidRootPart.CanCollide = false
end)
wait(.1)
local bambam = Instance.new("BodyThrust")
bambam.Parent = game.Players.LocalPlayer.Character.HumanoidRootPart
bambam.Force = Vector3.new(power,0,power)
bambam.Location = game.Players.LocalPlayer.Character.HumanoidRootPart.Position
   else
   power = 0
   weld1 = game.Players.LocalPlayer.Character.HumanoidRootPart.Position
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1123.33093, -479.219147, 2004.61536)
    wait(6)
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(weld1)
   
end
end)


b:Slider("WalkSpeed",{
    min = 16; -- min value of the slider
    max = 255; -- max value of the slider
    precise = true; -- max 2 decimals
},function(value)
    game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = value
end)

b:Slider("JumpPower",{
    min = 50; -- min value of the slider
    max = 255; -- max value of the slider
    precise = true; -- max 2 decimals
},function(value)
    game.Players.LocalPlayer.Character.Humanoid.JumpPower = value
end)

local b = w:CreateFolder("Visuals")

b:Button("Fullbright",function()
local Light = game:GetService("Lighting")

function dofullbright()
Light.Ambient = Color3.new(1, 1, 1)
Light.ColorShift_Bottom = Color3.new(1, 1, 1)
Light.ColorShift_Top = Color3.new(1, 1, 1)
end

dofullbright()

Light.LightingChanged:Connect(dofullbright)
end)

local epic = false
b:Toggle("ESP",function(bool)
   epic = bool
   if epic then
       ESP:Toggle(true)
   else
       ESP:Toggle(false)
end
end)

local b = w:CreateFolder("Weapons")

b:Button("Mod Weapons (Broken)",function()
while wait(1) do
for i,v in pairs(game.Players.LocalPlayer.Backpack:GetChildren()) do
if v:FindFirstChild("GunStates") then
local a =  require(v.GunStates)
a.MaxAmmo = math.huge
a.ReloadTime = 0
a.Range = math.huge
a.StoredAmmo = math.huge
else
return v
end
end
end
end)

b:Button("Give Pistol",function()
local args = {
    [1] = workspace.Prison_ITEMS.giver.M9.ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))

end)

b:Button("Give Shotgun",function()
local args = {
    [1] = workspace.Prison_ITEMS.giver["Remington 870"].ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))

end)

b:Button("Give AR (SWAT)",function()
local args = {
    [1] = workspace.Prison_ITEMS.giver.M4A1.ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))

end)-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Prison_ITEMS.giver.M4A1.ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))


b:Button("Give AK-47",function()
local args = {
    [1] = workspace.Prison_ITEMS.giver["AK-47"].ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))

end)

b:Button("Give All",function()
local args = {
    [1] = workspace.Prison_ITEMS.giver["AK-47"].ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))
wait()
local args = {
    [1] = workspace.Prison_ITEMS.giver.M4A1.ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))
wait()
local args = {
    [1] = workspace.Prison_ITEMS.giver["Remington 870"].ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))
wait()
local args = {
    [1] = workspace.Prison_ITEMS.giver.M9.ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))

end)



local b = w:CreateFolder("Teleports")
b:Button("Prison - Inside",function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(925.144592, 99.9899826, 2363.95288)
end)

b:Button("Prison - Outside",function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(389.373108, 88.0931778, 2215.40552)
end)

b:Button("Police Area",function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(811.329041, 99.9900055, 2251.79761)
end)

b:Button("CrimBase - Inside",function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-924.948853, 94.1287842, 2063.8291)
end)

b:Button("CrimBase - Outside",function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-848.809326, 94.4760513, 2087.37549)
end)

b:Button("City",function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-324.795837, 118.838844, 1993.96973)
end)

b:Button("Forest",function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(568.923462, 48.4358826, 1586.08228)
end)

b:Button("Residential Area",function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-296.741089, 67.4020691, 2514.67163)
end)

b:Button("Debug Area",function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(881.492249, 27.7899876, 2351.25146)
end)

local b = w:CreateFolder("Team Changer")

b:Button("Inmate Team",function()
    Workspace.Remote.TeamEvent:FireServer("Bright orange")
end)

b:Button("Guard Team",function()
    Workspace.Remote.TeamEvent:FireServer("Bright blue")
end)

b:Button("Neutral Team",function()
    Workspace.Remote.TeamEvent:FireServer("Medium stone grey")
end)

b:Button("Criminal Team",function()
    weld02 = game.Players.LocalPlayer.Character.HumanoidRootPart.Position
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-919.958, 95.327, 2138.189)
    wait(0.075)
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(weld02)
end)

local b = w:CreateFolder("Misc")

b:Button("Btools",function()
local tool1 = Instance.new("HopperBin",game.Players.LocalPlayer.Backpack)
local tool2 = Instance.new("HopperBin",game.Players.LocalPlayer.Backpack)
local tool3 = Instance.new("HopperBin",game.Players.LocalPlayer.Backpack)
local tool4 = Instance.new("HopperBin",game.Players.LocalPlayer.Backpack)
local tool5 = Instance.new("HopperBin",game.Players.LocalPlayer.Backpack)
tool1.BinType = "Clone"
tool2.BinType = "GameTool"
tool3.BinType = "Hammer"
tool4.BinType = "Script"
tool5.BinType = "Grab"
end)

b:Button("Inf Yeild",function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)

b:Button("Remove All Doors",function()
game.Workspace.Doors.door_v3:Destroy()
game.Workspace.Doors.door_v3:Destroy()
game.Workspace.Doors.door_v3_small:Destroy()
game.Workspace.Doors.door_v3_small:Destroy()
game.Workspace.Doors.door_v3_small:Destroy()
game.Workspace.Doors.door_v3:Destroy()
game.Workspace.Doors.door_v3_ct:Destroy()
game.Workspace.Doors.door_v3_cellblock1:Destroy()
game.Workspace.Doors.door_v3:Destroy()
game.Workspace.Doors.small:Destroy()
game.Workspace.Doors.door_v3:Destroy()
end)

b:Button("Invisible",function()
    local player = game.Players.LocalPlayer
position     = player.Character.HumanoidRootPart.Position
wait(0.1)
player.Character:MoveTo(position + Vector3.new(0, 1000000, 0))
wait(0.1)
humanoidrootpart = player.Character.HumanoidRootPart:clone()
wait(0.1)
player.Character.HumanoidRootPart:Destroy()
humanoidrootpart.Parent = player.Character
player.Character:MoveTo(position)
wait()
-- Remove this if you want to see yourself (others still won't see you)
game.Players.LocalPlayer.Character.Torso.Transparency = 1
game.Players.LocalPlayer.Character.Head.Transparency  = 1
game.Players.LocalPlayer.Character["Left Arm"].Transparency = 1
game.Players.LocalPlayer.Character["Right Arm"].Transparency = 1
game.Players.LocalPlayer.Character["Left Leg"].Transparency = 1
game.Players.LocalPlayer.Character["Right Leg"].Transparency = 1
game.Players.LocalPlayer.Character.Humanoid:RemoveAccessories()
game.Players.LocalPlayer.Character.Head.face:Remove()
end)

local b = w:CreateFolder("Other")

b:Label("Discord - Hapy#7232",{
TextSize = 17; -- Self Explainin
TextColor = Color3.fromRGB(255,255,255); -- Self Explaining
BgColor = Color3.fromRGB(69,69,69); -- Self Explaining

}) 


b:DestroyGui()
